linters-settings:
  errcheck:
    ignore: fmt:.*,go.uber.org/zap:Sync
  govet:
    check-shadowing: true
  goimports:
    # put imports beginning with prefix after 3rd-party packages;
    # it's a comma-separated list of prefixes
    local-prefixes: github.com/trussworks/my-cli-tool

linters:
  enable:
    - errcheck
    - gocritic
    - gofmt
    - goimports
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - revive
  disable:
    - gosimple #deprecated https://github.com/golangci/golangci-lint/issues/357
    - unused #deprecated https://github.com/dominikh/go-tools/tree/master/cmd/unused
    - golint
    - varcheck
    - deadcode
    - structcheck
  fast: false

issues:
  # golangci-lint excludes by default some checks they consider "annoying"
  # A better practice is for each repo to choose which ones to disable
  exclude-use-default: false
  fix: true

run:
  modules-download-mode: readonly
