version: 2.1
references:
  circleci: &circleci trussworks/circleci:1f3f01b9b8bdb160380a3b338e8b23c7dda067de
jobs:
  build:
    docker:
    - auth:
        password: $DOCKER_PASSWORD
        username: $DOCKER_USERNAME
      image: *circleci
    steps:
    - checkout
    - restore_cache:
        keys:
          - pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
          - go-mod-sources-v1-{{ checksum "go.sum" }}
    - run: make pre_commit
    - run: make test
    - save_cache:
        key: pre-commit-dot-cache-{{ checksum ".pre-commit-config.yaml" }}
        paths:
          - ~/.cache/pre-commit
    - save_cache:
        key: go-mod-sources-v1-{{ checksum "go.sum" }}
        paths:
          - "~/go/pkg/mod"
workflows:
  build:
    jobs:
    - build:
        context:
          - org-global
  version: 2.1
