#!/usr/bin/env bash

set -eux

version="$(git rev-parse HEAD)"

docker image build -t ecr-scan-builder:"${version}" .
docker container run --rm -it -v "$(PWD)":/app ecr-scan-builder:"${version}" go build -o bin/ecr-scan .
