#!/usr/bin/env bash

set -ux

readonly s3_bucket="$1"
version="$(git rev-parse HEAD)"
zip_file="${version}".zip

zip -j "${zip_file}" ./bin/ecr-scan || exit
aws s3 cp --sse AES256 "${zip_file}" s3://"${s3_bucket}"/ecr-scan/"${zip_file}"
